cors:
  originPatterns: http://estudo.eruido.com.br
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:erudio}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:abcd1234}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
