cors:
  originPatterns: http://localhost:8080,http://localhost:8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:erudio}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:abcd1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: false

logging:
  level:
    br.github: DEBUG

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
